apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: blinkt-sa
  name: blinkt-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: blinkt
  labels:
    app: blinkt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: blinkt-sa
  namespace: kube-system
